import type { PlayerProfile } from "../types";

export const PLAYERS: PlayerProfile[] = [
  {
    slug: "jude-bellingham",
    name: "Jude Bellingham",
    nation: "England",
    fifaCode: "ENG",
    position: "Midfielder",
    archetype: "Complete modern midfielder",
    whyExcited:
      "Combines leadership, technical skill, athleticism, and maturity far beyond his age.",
    watchFor: "Late runs into the box and midfield control.",
    similarEnergy: "Young Steven Gerrard meets modern tactical intelligence.",
    featured: true,
  },
  {
    slug: "jamal-musiala",
    name: "Jamal Musiala",
    nation: "Germany",
    fifaCode: "GER",
    position: "Attacking Midfielder",
    archetype: "Creative dribbler",
    whyExcited:
      "One of the world's most unpredictable and fluid young attackers.",
    watchFor: "Tight-space dribbling and quick directional changes.",
    similarEnergy: "Street football creativity with elite composure.",
    featured: true,
  },
  {
    slug: "lamine-yamal",
    name: "Lamine Yamal",
    nation: "Spain",
    fifaCode: "ESP",
    position: "Winger",
    archetype: "Fearless wonderkid",
    whyExcited: "Playing at an elite level while still incredibly young.",
    watchFor: "One-on-one dribbling and daring decisions.",
    similarEnergy: "Teenage Neymar confidence.",
    featured: true,
  },
  {
    slug: "florian-wirtz",
    name: "Florian Wirtz",
    nation: "Germany",
    fifaCode: "GER",
    position: "Attacking Midfielder",
    archetype: "Creative playmaker",
    whyExcited: "Exceptional vision and calmness under pressure.",
    watchFor: "Through balls and intelligent movement.",
    similarEnergy: "Classic European creator with modern mobility.",
    featured: true,
  },
  {
    slug: "endrick",
    name: "Endrick",
    nation: "Brazil",
    fifaCode: "BRA",
    position: "Forward",
    archetype: "Explosive scorer",
    whyExcited:
      "One of Brazil's most hyped young attacking prospects in years.",
    watchFor: "Direct attacking runs and powerful finishing.",
    similarEnergy: "Raw Brazilian attacking chaos.",
    featured: true,
  },
  {
    slug: "lionel-messi",
    name: "Lionel Messi",
    nation: "Argentina",
    fifaCode: "ARG",
    position: "Forward",
    archetype: "Generational playmaker",
    whyExcited: "Still orchestrating Argentina's attack in his final chapters.",
    watchFor: "Free kicks, final passes, and moments of pure genius.",
    similarEnergy: "The standard every attacker is measured against.",
    featured: true,
  },
  {
    slug: "julian-alvarez",
    name: "Julián Álvarez",
    nation: "Argentina",
    fifaCode: "ARG",
    position: "Forward",
    archetype: "Relentless presser",
    whyExcited: "Champion mentality with intelligent movement off the ball.",
    watchFor: "High pressing triggers and clinical finishing.",
    similarEnergy: "Modern striker who makes everyone around him better.",
  },
  {
    slug: "enzo-fernandez",
    name: "Enzo Fernández",
    nation: "Argentina",
    fifaCode: "ARG",
    position: "Midfielder",
    archetype: "Deep-lying conductor",
    whyExcited: "World Cup-winning composure in the engine room.",
    watchFor: "Progressive passing and tempo control.",
    similarEnergy: "Young midfield general with tournament pedigree.",
  },
  {
    slug: "alexis-mac-allister",
    name: "Alexis Mac Allister",
    nation: "Argentina",
    fifaCode: "ARG",
    position: "Midfielder",
    archetype: "Technical linker",
    whyExcited: "Connects Argentina's midfield and attack with subtle quality.",
    watchFor: "Third-man runs and disguised passes.",
    similarEnergy: "Quiet excellence in a star-studded squad.",
  },
  {
    slug: "kylian-mbappe",
    name: "Kylian Mbappé",
    nation: "France",
    fifaCode: "FRA",
    position: "Forward",
    archetype: "Elite speed threat",
    whyExcited: "The face of France's next era with devastating pace.",
    watchFor: "Counterattacks and runs in behind.",
    similarEnergy: "Thierry Henry's explosiveness at a higher gear.",
    featured: true,
  },
  {
    slug: "eduardo-camavinga",
    name: "Eduardo Camavinga",
    nation: "France",
    fifaCode: "FRA",
    position: "Midfielder",
    archetype: "Versatile ball-winner",
    whyExcited: "Elite athleticism with growing tactical maturity.",
    watchFor: "Recovery runs and box-to-box transitions.",
    similarEnergy: "Modern destroyer who can play anywhere in midfield.",
  },
  {
    slug: "aurelien-tchouameni",
    name: "Aurélien Tchouaméni",
    nation: "France",
    fifaCode: "FRA",
    position: "Midfielder",
    archetype: "Defensive anchor",
    whyExcited: "France's midfield shield with composure under pressure.",
    watchFor: "Interceptions and long-range passing.",
    similarEnergy: "Patrick Vieira's presence with modern technique.",
  },
  {
    slug: "william-saliba",
    name: "William Saliba",
    nation: "France",
    fifaCode: "FRA",
    position: "Defender",
    archetype: "Dominant centre-back",
    whyExcited: "Aerial dominance and calm build-up from the back.",
    watchFor: "One-on-one defending and progressive carries.",
    similarEnergy: "The defensive rock France builds around.",
  },
  {
    slug: "vinicius-junior",
    name: "Vinícius Júnior",
    nation: "Brazil",
    fifaCode: "BRA",
    position: "Winger",
    archetype: "Chaos creator",
    whyExcited: "Brazil's new attacking centerpiece with elite dribbling.",
    watchFor: "One-on-one duels and cutbacks from the left.",
    similarEnergy: "Ronaldinho flair with modern end product.",
    featured: true,
  },
  {
    slug: "rodrygo",
    name: "Rodrygo",
    nation: "Brazil",
    fifaCode: "BRA",
    position: "Forward",
    archetype: "Clinical finisher",
    whyExcited: "Big-game goals and intelligent movement in the box.",
    watchFor: "Late runs and composure in tight spaces.",
    similarEnergy: "The perfect complement to Vinícius's chaos.",
  },
  {
    slug: "bruno-guimaraes",
    name: "Bruno Guimarães",
    nation: "Brazil",
    fifaCode: "BRA",
    position: "Midfielder",
    archetype: "Midfield engine",
    whyExcited: "Carries Brazil through transitions with power and vision.",
    watchFor: "Ball carrying and defensive recoveries.",
    similarEnergy: "The heartbeat of Brazil's modern midfield.",
  },
  {
    slug: "bukayo-saka",
    name: "Bukayo Saka",
    nation: "England",
    fifaCode: "ENG",
    position: "Winger",
    archetype: "Direct wide threat",
    whyExcited: "England's most consistent wide outlet with elite 1v1 ability.",
    watchFor: "Cut-inside finishes and defensive work rate.",
    similarEnergy: "Raheem Sterling's directness with more end product.",
  },
  {
    slug: "phil-foden",
    name: "Phil Foden",
    nation: "England",
    fifaCode: "ENG",
    position: "Attacking Midfielder",
    archetype: "Technical creator",
    whyExcited: "Silky touches and creativity in tight spaces.",
    watchFor: "Half-space dribbles and combination play.",
    similarEnergy: "David Silva's elegance with more dynamism.",
  },
  {
    slug: "harry-kane",
    name: "Harry Kane",
    nation: "England",
    fifaCode: "ENG",
    position: "Forward",
    archetype: "Complete striker",
    whyExcited: "Elite finishing paired with playmaking from deep.",
    watchFor: "Hold-up play and through balls to runners.",
    similarEnergy: "The focal point England's attack revolves around.",
  },
  {
    slug: "kai-havertz",
    name: "Kai Havertz",
    nation: "Germany",
    fifaCode: "GER",
    position: "Forward",
    archetype: "Intelligent runner",
    whyExcited: "Versatile forward who links play and finds space.",
    watchFor: "Late box arrivals and link-up combinations.",
    similarEnergy: "Tactical intelligence over raw flair.",
  },
  {
    slug: "antonio-rudiger",
    name: "Antonio Rüdiger",
    nation: "Germany",
    fifaCode: "GER",
    position: "Defender",
    archetype: "Aggressive leader",
    whyExcited: "Sets the tone with intensity and aerial dominance.",
    watchFor: "Stepping out of defense and commanding the back line.",
    similarEnergy: "The emotional engine of Germany's rebuild.",
  },
  {
    slug: "pedri",
    name: "Pedri",
    nation: "Spain",
    fifaCode: "ESP",
    position: "Midfielder",
    archetype: "Possession maestro",
    whyExcited: "Spain's midfield metronome with otherworldly touch.",
    watchFor: "One-touch passing and press resistance.",
    similarEnergy: "Iniesta's calm in a faster modern game.",
    featured: true,
  },
  {
    slug: "nico-williams",
    name: "Nico Williams",
    nation: "Spain",
    fifaCode: "ESP",
    position: "Winger",
    archetype: "Direct wide runner",
    whyExcited: "Explosive pace that stretches any defense.",
    watchFor: "Overlapping runs and cutback assists.",
    similarEnergy: "Spain's answer to the modern wide speed threat.",
  },
  {
    slug: "rodri",
    name: "Rodri",
    nation: "Spain",
    fifaCode: "ESP",
    position: "Midfielder",
    archetype: "Midfield maestro",
    whyExcited: "The world's best holding midfielder controls every tempo.",
    watchFor: "Positional discipline and long-range passing.",
    similarEnergy: "Busquets' intelligence with more physical presence.",
    featured: true,
  },
  {
    slug: "bruno-fernandes",
    name: "Bruno Fernandes",
    nation: "Portugal",
    fifaCode: "POR",
    position: "Midfielder",
    archetype: "Creative catalyst",
    whyExcited: "Portugal's creative hub with vision and set-piece quality.",
    watchFor: "Through balls, long shots, and leadership.",
    similarEnergy: "The playmaker Portugal builds its attack around.",
    featured: true,
  },
  {
    slug: "rafael-leao",
    name: "Rafael Leão",
    nation: "Portugal",
    fifaCode: "POR",
    position: "Winger",
    archetype: "Chaos creator",
    whyExcited: "Explosive dribbling that can unlock any defense.",
    watchFor: "Direct runs and power in 1v1 situations.",
    similarEnergy: "Portuguese flair at maximum velocity.",
    featured: true,
  },
  {
    slug: "joao-neves",
    name: "João Neves",
    nation: "Portugal",
    fifaCode: "POR",
    position: "Midfielder",
    archetype: "Young midfield anchor",
    whyExcited: "Remarkable maturity for a player still establishing himself.",
    watchFor: "Ball recovery and progressive passing.",
    similarEnergy: "Portugal's next-generation midfield foundation.",
  },
  {
    slug: "bernardo-silva",
    name: "Bernardo Silva",
    nation: "Portugal",
    fifaCode: "POR",
    position: "Midfielder",
    archetype: "Technical orchestrator",
    whyExcited: "Elite close control and tactical intelligence.",
    watchFor: "Half-space manipulation and pressing triggers.",
    similarEnergy: "The connective tissue in Portugal's attack.",
  },
  {
    slug: "achraf-hakimi",
    name: "Achraf Hakimi",
    nation: "Morocco",
    fifaCode: "MAR",
    position: "Defender",
    archetype: "Attacking full-back",
    whyExcited: "One of the world's most dangerous wide defenders.",
    watchFor: "Overlapping runs and recovery pace.",
    similarEnergy: "Cafu's attacking threat from the right flank.",
  },
  {
    slug: "sofyan-amrabat",
    name: "Sofyan Amrabat",
    nation: "Morocco",
    fifaCode: "MAR",
    position: "Midfielder",
    archetype: "Defensive shield",
    whyExcited: "Morocco's midfield anchor with relentless work rate.",
    watchFor: "Ball-winning and press resistance.",
    similarEnergy: "The engine behind Morocco's defensive structure.",
  },
  {
    slug: "brahim-diaz",
    name: "Brahim Díaz",
    nation: "Morocco",
    fifaCode: "MAR",
    position: "Winger",
    archetype: "Creative spark",
    whyExcited: "Technical flair that unlocks tight defensive blocks.",
    watchFor: "Close control and incisive passing in the final third.",
    similarEnergy: "Morocco's creative wildcard off the bench.",
  },
  {
    slug: "luka-modric",
    name: "Luka Modrić",
    nation: "Croatia",
    fifaCode: "CRO",
    position: "Midfielder",
    archetype: "Veteran legend",
    whyExcited:
      "A generational midfielder in the twilight of an iconic career.",
    watchFor: "Tempo control and outside-of-boot passes.",
    similarEnergy: "The soul of Croatian football.",
    featured: true,
  },
  {
    slug: "josko-gvardiol",
    name: "Joško Gvardiol",
    nation: "Croatia",
    fifaCode: "CRO",
    position: "Defender",
    archetype: "Modern ball-playing defender",
    whyExcited: "Elite left-footed defender comfortable in any system.",
    watchFor: "Progressive carries and composure under pressure.",
    similarEnergy: "Croatia's defensive cornerstone for the next decade.",
  },
  {
    slug: "mateo-kovacic",
    name: "Mateo Kovačić",
    nation: "Croatia",
    fifaCode: "CRO",
    position: "Midfielder",
    archetype: "Press-resistant metronome",
    whyExcited: "Silky ball retention that keeps Croatia ticking.",
    watchFor: "One-touch combinations and dribbles out of pressure.",
    similarEnergy: "The midfield glue in Croatia's transition era.",
  },
  {
    slug: "takefusa-kubo",
    name: "Takefusa Kubo",
    nation: "Japan",
    fifaCode: "JPN",
    position: "Winger",
    archetype: "Technical wide creator",
    whyExcited: "Japan's most gifted dribbler with La Liga pedigree.",
    watchFor: "Cut-inside shots and combination play on the right.",
    similarEnergy: "Japan's creative outlet against organized defenses.",
  },
  {
    slug: "kaoru-mitoma",
    name: "Kaoru Mitoma",
    nation: "Japan",
    fifaCode: "JPN",
    position: "Winger",
    archetype: "Chaos creator",
    whyExcited: "Unpredictable dribbling that thrives in transition.",
    watchFor: "Direct runs and composure in the penalty area.",
    similarEnergy: "The Premier League export Japan trusts most.",
    featured: true,
  },
  {
    slug: "wataru-endo",
    name: "Wataru Endō",
    nation: "Japan",
    fifaCode: "JPN",
    position: "Midfielder",
    archetype: "Disciplined anchor",
    whyExcited: "Japan's midfield shield with elite positioning.",
    watchFor: "Interceptions and simple, effective distribution.",
    similarEnergy: "The tactical discipline Japan is built on.",
  },
  {
    slug: "virgil-van-dijk",
    name: "Virgil van Dijk",
    nation: "Netherlands",
    fifaCode: "NED",
    position: "Defender",
    archetype: "Commanding centre-back",
    whyExcited: "Still one of the world's most complete defenders.",
    watchFor: "Aerial duels and calm build-up play.",
    similarEnergy: "The leader Netherlands organizes around.",
  },
  {
    slug: "xavi-simons",
    name: "Xavi Simons",
    nation: "Netherlands",
    fifaCode: "NED",
    position: "Attacking Midfielder",
    archetype: "Creative spark",
    whyExcited: "Dutch football's brightest young creative talent.",
    watchFor: "Between-the-lines movement and incisive passing.",
    similarEnergy: "The next chapter of Dutch technical football.",
  },
  {
    slug: "cody-gakpo",
    name: "Cody Gakpo",
    nation: "Netherlands",
    fifaCode: "NED",
    position: "Forward",
    archetype: "Versatile attacker",
    whyExcited: "Clinical finishing from multiple attacking positions.",
    watchFor: "Left-footed strikes and intelligent runs.",
    similarEnergy: "The flexible weapon in Netherlands' attack.",
  },
  {
    slug: "cristiano-ronaldo",
    name: "Cristiano Ronaldo",
    nation: "Portugal",
    fifaCode: "POR",
    position: "Forward",
    archetype: "Veteran legend",
    whyExcited: "One of football's greatest ever, still hunting records.",
    watchFor: "Movement in the box and set-piece threat.",
    similarEnergy: "The ultimate tournament mentality.",
    featured: true,
  },
  {
    slug: "khvicha-kvaratskhelia",
    name: "Khvicha Kvaratskhelia",
    nation: "Georgia",
    position: "Winger",
    archetype: "Star-driven underdog",
    whyExcited: "Georgia's talisman with world-class dribbling and flair.",
    watchFor: "Left-footed strikes and fearless 1v1 moments.",
    similarEnergy: "A nation carried by one generational talent.",
  },
];
