type SquadSeedEntry = {
  status: "announced" | "pending";
  managerName?: string;
  managerNationality?: string;
};

/** Curated manager & squad metadata (migrated from lib/tournament/seed/squads.ts). */
export const SQUAD_SEED_DATA: Record<string, SquadSeedEntry> = {
  MEX: { status: "announced", managerName: "Javier Aguirre", managerNationality: "Mexico" },
  RSA: { status: "announced", managerName: "Hugo Broos", managerNationality: "Belgium" },
  KOR: { status: "announced", managerName: "Hong Myung-bo", managerNationality: "South Korea" },
  CZE: { status: "announced", managerName: "Ivan Hašek", managerNationality: "Czech Republic" },
  CAN: { status: "announced", managerName: "Jesse Marsch", managerNationality: "United States" },
  BIH: { status: "announced", managerName: "Sergej Barbarez", managerNationality: "Bosnia & Herzegovina" },
  QAT: { status: "announced", managerName: "Carlos Queiroz", managerNationality: "Portugal" },
  SUI: { status: "announced", managerName: "Murat Yakin", managerNationality: "Switzerland" },
  BRA: { status: "announced", managerName: "Carlo Ancelotti", managerNationality: "Italy" },
  MAR: { status: "announced", managerName: "Walid Regragui", managerNationality: "Morocco" },
  HAI: { status: "announced", managerName: "Sébastien Migné", managerNationality: "France" },
  SCO: { status: "announced", managerName: "Steve Clarke", managerNationality: "Scotland" },
  USA: { status: "announced", managerName: "Mauricio Pochettino", managerNationality: "Argentina" },
  PAR: { status: "announced", managerName: "Gustavo Alfaro", managerNationality: "Argentina" },
  AUS: { status: "announced", managerName: "Tony Popovic", managerNationality: "Australia" },
  TUR: { status: "announced", managerName: "Vincenzo Montella", managerNationality: "Italy" },
  GER: { status: "announced", managerName: "Julian Nagelsmann", managerNationality: "Germany" },
  CUW: { status: "announced", managerName: "Dick Advocaat", managerNationality: "Netherlands" },
  CIV: { status: "announced", managerName: "Emerse Faé", managerNationality: "Ivory Coast" },
  ECU: { status: "announced", managerName: "Sebastián Beccacece", managerNationality: "Argentina" },
  NED: { status: "announced", managerName: "Ronald Koeman", managerNationality: "Netherlands" },
  JPN: { status: "announced", managerName: "Hajime Moriyasu", managerNationality: "Japan" },
  SWE: { status: "announced", managerName: "Graham Potter", managerNationality: "England" },
  TUN: { status: "announced", managerName: "Sami Trabelsi", managerNationality: "Tunisia" },
  BEL: { status: "announced", managerName: "Rudi Garcia", managerNationality: "France" },
  EGY: { status: "announced", managerName: "Hossam Hassan", managerNationality: "Egypt" },
  IRN: { status: "announced", managerName: "Amir Ghalenoei", managerNationality: "Iran" },
  NZL: { status: "announced", managerName: "Darren Bazeley", managerNationality: "England" },
  ESP: { status: "announced", managerName: "Luis de la Fuente", managerNationality: "Spain" },
  CPV: { status: "announced", managerName: "Bubista", managerNationality: "Cape Verde" },
  KSA: { status: "announced", managerName: "Hervé Renard", managerNationality: "France" },
  URU: { status: "announced", managerName: "Marcelo Bielsa", managerNationality: "Argentina" },
  FRA: { status: "announced", managerName: "Didier Deschamps", managerNationality: "France" },
  SEN: { status: "announced", managerName: "Pape Thiaw", managerNationality: "Senegal" },
  IRQ: { status: "announced", managerName: "Jesús Casas", managerNationality: "Spain" },
  NOR: { status: "announced", managerName: "Ståle Solbakken", managerNationality: "Norway" },
  ARG: { status: "announced", managerName: "Lionel Scaloni", managerNationality: "Argentina" },
  ALG: { status: "announced", managerName: "Djamel Belmadi", managerNationality: "Algeria" },
  AUT: { status: "announced", managerName: "Ralf Rangnick", managerNationality: "Austria" },
  JOR: { status: "announced", managerName: "Hussein Ammouta", managerNationality: "Jordan" },
  POR: { status: "announced", managerName: "Roberto Martínez", managerNationality: "Spain" },
  COD: { status: "announced", managerName: "Sébastien Desabre", managerNationality: "France" },
  UZB: { status: "announced", managerName: "Slavisa Jokanović", managerNationality: "Serbia" },
  COL: { status: "announced", managerName: "Néstor Lorenzo", managerNationality: "Argentina" },
  ENG: { status: "announced", managerName: "Thomas Tuchel", managerNationality: "Germany" },
  CRO: { status: "announced", managerName: "Zlatko Dalić", managerNationality: "Croatia" },
  GHA: { status: "announced", managerName: "Otto Addo", managerNationality: "Germany" },
  PAN: { status: "announced", managerName: "Julio Dely Valdés", managerNationality: "Panama" },
};
