export const GROUP_LETTERS = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
] as const;

export type GroupLetter = (typeof GROUP_LETTERS)[number];

export type Wc2026Nation = {
  fifaCode: string;
  displayName: string;
  group: GroupLetter;
  confed: string;
  continent: string;
  aliases?: string[];
};

export const WC2026_NATIONS: Wc2026Nation[] = [
  {
    fifaCode: "MEX",
    displayName: "Mexico",
    group: "A",
    confed: "CONCACAF",
    continent: "North America",
  },
  {
    fifaCode: "CZE",
    displayName: "Czechia",
    group: "A",
    confed: "UEFA",
    continent: "Europe",
    aliases: ["Czech Republic"],
  },
  {
    fifaCode: "RSA",
    displayName: "South Africa",
    group: "A",
    confed: "CAF",
    continent: "Africa",
  },
  {
    fifaCode: "KOR",
    displayName: "South Korea",
    group: "A",
    confed: "AFC",
    continent: "Asia",
    aliases: ["Korea Republic"],
  },
  {
    fifaCode: "BIH",
    displayName: "Bosnia & Herzegovina",
    group: "B",
    confed: "UEFA",
    continent: "Europe",
    aliases: ["Bosnia and Herzegovina"],
  },
  {
    fifaCode: "CAN",
    displayName: "Canada",
    group: "B",
    confed: "CONCACAF",
    continent: "North America",
  },
  {
    fifaCode: "QAT",
    displayName: "Qatar",
    group: "B",
    confed: "AFC",
    continent: "Asia",
  },
  {
    fifaCode: "SUI",
    displayName: "Switzerland",
    group: "B",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "BRA",
    displayName: "Brazil",
    group: "C",
    confed: "CONMEBOL",
    continent: "South America",
  },
  {
    fifaCode: "HAI",
    displayName: "Haiti",
    group: "C",
    confed: "CONCACAF",
    continent: "North America",
  },
  {
    fifaCode: "MAR",
    displayName: "Morocco",
    group: "C",
    confed: "CAF",
    continent: "Africa",
  },
  {
    fifaCode: "SCO",
    displayName: "Scotland",
    group: "C",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "AUS",
    displayName: "Australia",
    group: "D",
    confed: "AFC",
    continent: "Oceania",
  },
  {
    fifaCode: "PAR",
    displayName: "Paraguay",
    group: "D",
    confed: "CONMEBOL",
    continent: "South America",
  },
  {
    fifaCode: "TUR",
    displayName: "Türkiye",
    group: "D",
    confed: "UEFA",
    continent: "Europe",
    aliases: ["Turkey", "Turkiye"],
  },
  {
    fifaCode: "USA",
    displayName: "USA",
    group: "D",
    confed: "CONCACAF",
    continent: "North America",
    aliases: ["United States"],
  },
  {
    fifaCode: "CUW",
    displayName: "Curaçao",
    group: "E",
    confed: "CONCACAF",
    continent: "North America",
    aliases: ["Curacao"],
  },
  {
    fifaCode: "ECU",
    displayName: "Ecuador",
    group: "E",
    confed: "CONMEBOL",
    continent: "South America",
  },
  {
    fifaCode: "GER",
    displayName: "Germany",
    group: "E",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "CIV",
    displayName: "Côte d'Ivoire",
    group: "E",
    confed: "CAF",
    continent: "Africa",
    aliases: ["Ivory Coast", "Cote d'Ivoire"],
  },
  {
    fifaCode: "JPN",
    displayName: "Japan",
    group: "F",
    confed: "AFC",
    continent: "Asia",
  },
  {
    fifaCode: "NED",
    displayName: "Netherlands",
    group: "F",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "SWE",
    displayName: "Sweden",
    group: "F",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "TUN",
    displayName: "Tunisia",
    group: "F",
    confed: "CAF",
    continent: "Africa",
  },
  {
    fifaCode: "BEL",
    displayName: "Belgium",
    group: "G",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "EGY",
    displayName: "Egypt",
    group: "G",
    confed: "CAF",
    continent: "Africa",
  },
  {
    fifaCode: "IRN",
    displayName: "Iran",
    group: "G",
    confed: "AFC",
    continent: "Asia",
  },
  {
    fifaCode: "NZL",
    displayName: "New Zealand",
    group: "G",
    confed: "OFC",
    continent: "Oceania",
  },
  {
    fifaCode: "CPV",
    displayName: "Cabo Verde",
    group: "H",
    confed: "CAF",
    continent: "Africa",
    aliases: ["Cape Verde"],
  },
  {
    fifaCode: "KSA",
    displayName: "Saudi Arabia",
    group: "H",
    confed: "AFC",
    continent: "Asia",
  },
  {
    fifaCode: "ESP",
    displayName: "Spain",
    group: "H",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "URU",
    displayName: "Uruguay",
    group: "H",
    confed: "CONMEBOL",
    continent: "South America",
  },
  {
    fifaCode: "FRA",
    displayName: "France",
    group: "I",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "IRQ",
    displayName: "Iraq",
    group: "I",
    confed: "AFC",
    continent: "Asia",
  },
  {
    fifaCode: "NOR",
    displayName: "Norway",
    group: "I",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "SEN",
    displayName: "Senegal",
    group: "I",
    confed: "CAF",
    continent: "Africa",
  },
  {
    fifaCode: "ALG",
    displayName: "Algeria",
    group: "J",
    confed: "CAF",
    continent: "Africa",
  },
  {
    fifaCode: "ARG",
    displayName: "Argentina",
    group: "J",
    confed: "CONMEBOL",
    continent: "South America",
  },
  {
    fifaCode: "AUT",
    displayName: "Austria",
    group: "J",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "JOR",
    displayName: "Jordan",
    group: "J",
    confed: "AFC",
    continent: "Asia",
  },
  {
    fifaCode: "COL",
    displayName: "Colombia",
    group: "K",
    confed: "CONMEBOL",
    continent: "South America",
  },
  {
    fifaCode: "COD",
    displayName: "DR Congo",
    group: "K",
    confed: "CAF",
    continent: "Africa",
    aliases: ["Congo DR", "Democratic Republic of the Congo"],
  },
  {
    fifaCode: "POR",
    displayName: "Portugal",
    group: "K",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "UZB",
    displayName: "Uzbekistan",
    group: "K",
    confed: "AFC",
    continent: "Asia",
  },
  {
    fifaCode: "CRO",
    displayName: "Croatia",
    group: "L",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "ENG",
    displayName: "England",
    group: "L",
    confed: "UEFA",
    continent: "Europe",
  },
  {
    fifaCode: "GHA",
    displayName: "Ghana",
    group: "L",
    confed: "CAF",
    continent: "Africa",
  },
  {
    fifaCode: "PAN",
    displayName: "Panama",
    group: "L",
    confed: "CONCACAF",
    continent: "North America",
  },
];

export const WC2026_NATIONS_BY_FIFA = new Map(
  WC2026_NATIONS.map((nation) => [nation.fifaCode, nation]),
);
