/** ISO 3166-1 alpha-2 codes for BSD `nationality_code` filters. */
const FIFA_TO_ISO2: Record<string, string> = {
  ALG: "DZ",
  ARG: "AR",
  AUS: "AU",
  AUT: "AT",
  BEL: "BE",
  BIH: "BA",
  BRA: "BR",
  CAN: "CA",
  CPV: "CV",
  COL: "CO",
  CIV: "CI",
  CRO: "HR",
  CUW: "CW",
  CZE: "CZ",
  COD: "CD",
  ECU: "EC",
  EGY: "EG",
  ESP: "ES",
  ENG: "GB",
  FRA: "FR",
  GER: "DE",
  GHA: "GH",
  HAI: "HT",
  IRN: "IR",
  IRQ: "IQ",
  JOR: "JO",
  JPN: "JP",
  KOR: "KR",
  KSA: "SA",
  MAR: "MA",
  MEX: "MX",
  NED: "NL",
  NZL: "NZ",
  NOR: "NO",
  PAN: "PA",
  PAR: "PY",
  POR: "PT",
  QAT: "QA",
  RSA: "ZA",
  SCO: "GB",
  SEN: "SN",
  SUI: "CH",
  SWE: "SE",
  TUN: "TN",
  TUR: "TR",
  USA: "US",
  URU: "UY",
  UZB: "UZ",
};

export const BSD_TEAM_NAME_ALIASES: Record<string, string[]> = {
  USA: ["united states"],
  KOR: ["south korea", "korea republic"],
  CIV: ["côte d'ivoire", "cote d'ivoire", "ivory coast"],
  CPV: ["cabo verde", "cape verde"],
  COD: ["dr congo", "congo dr", "democratic republic of the congo"],
  TUR: ["türkiye", "turkiye"],
  CZE: ["czechia", "czech republic"],
  RSA: ["south africa"],
  SCO: ["scotland"],
  ENG: ["england"],
  NED: ["netherlands"],
  SUI: ["switzerland"],
  GER: ["germany"],
  BIH: ["bosnia and herzegovina", "bosnia & herzegovina"],
};

export function iso2ForFifa(fifaCode: string) {
  return FIFA_TO_ISO2[fifaCode.toUpperCase()];
}
