/** Maps player JSON / legacy country strings to FIFA codes. */
export const COUNTRY_NAME_TO_FIFA: Record<string, string> = {
  Norway: "NOR",
  England: "ENG",
  France: "FRA",
  Brazil: "BRA",
  Portugal: "POR",
  Croatia: "CRO",
  Egypt: "EGY",
  Germany: "GER",
  Senegal: "SEN",
  Belgium: "BEL",
  "Bosnia and Herzegovina": "BIH",
  "South Korea": "KOR",
  Austria: "AUT",
  Japan: "JPN",
  Czechia: "CZE",
  Scotland: "SCO",
  Curaçao: "CUW",
  Haiti: "HAI",
  Qatar: "QAT",
  Turkey: "TUR",
  Sweden: "SWE",
  Switzerland: "SUI",
  Tunisia: "TUN",
  "Saudi Arabia": "KSA",
  "New Zealand": "NZL",
  "Cabo Verde": "CPV",
  "Congo DR": "COD",
  "Côte d'Ivoire": "CIV",
};
